services:

  pg:
    image: postgres
    container_name: poll_pg
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pg_test:
    image: postgres
    environment:
      POSTGRES_DB: poll_db_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
